"""
AgenticState for ReAct Agent Loop (v3.0).
Extends v2.0 AgentState with agentic-specific fields.
"""

from typing import Annotated, Dict, List, TypedDict
from operator import add


class AgenticState(TypedDict, total=False):
    """State for the Agentic RAG ReAct loop."""

    # ── v2.0 fields (inherited from AgentState) ──────────────
    query: str
    search_sources: List[str]
    max_results_per_source: int

    rewritten_queries: List[str]
    search_results: Annotated[List[dict], add]
    fetched_contents: List[dict]
    per_source_summaries: Dict[str, str]

    final_answer: str
    citations: List[dict]

    conversation_history: List[dict]
    conversation_context: str

    status: str
    status_message: str
    logs: Annotated[List[str], add]
    errors: Annotated[List[str], add]
    stream_chunk: str

    # ── v3.0 agentic fields ──────────────────────────────────
    messages: Annotated[List[dict], add]
    """Raw LLM conversation messages (system, user, assistant, tool)."""

    tool_calls_made: int
    """Number of tool calls executed so far in this agent loop."""

    max_tool_calls: int
    """Budget: max allowed tool calls (default 12)."""

    observations: Annotated[List[dict], add]
    """Record of each observation: [{tool, content, ...}]."""

    agent_reasoning_trace: Annotated[List[str], add]
    """Agent's reasoning trace: ["Thought: ...", "Thought: ..."]."""

    evidence_sufficient: bool
    """Whether the agent has gathered enough evidence to answer."""

    agent_plan: str
    """Agent's current plan for information gathering."""

    pending_tool_calls: List[dict]
    """Tool calls generated by the agent that need execution."""

    agent_iteration: int
    """Current iteration count in the agent loop."""
